### ISSUE TITLE
[Network Meter] Negative data transferred during the session

### ISSUE THREAD

**Issue by zesquale** [raiguard/ModernGadgets#142]
Hello,

Firstly, I want to thank you for ModernGadgets, it is really useful and really good.
However, I think I found a bug in the Network Meter Gadget.
I have some negative values in the session part. See below : 
![image](https://user-images.githubusercontent.com/49090868/55273712-1f660b80-52cf-11e9-956b-1b653ebd04d6.png)

Feel free to contact me if you need additional information / tests.

**Comment by raiguard** [comment]
A few questions:

1. Are you using the NetMonitor service?
2. Have you ever reset the session or the totals using the reset button?
3. What happens if you refresh (middle-click) the gadget?

**Comment by zesquale** [comment]
1. No I'm not using it
2. Not tested, see point 3
3. When I refreshed the gadget, all values where back to 0. For the moment, all values are still positive.

During the last session where value falls into negatives, I transferred a lot of data (backup of the entire computer) so I may have exceeded the max value of the counter.

Best Regards.

**Comment by raiguard** [comment]
I'll poke around and see if I can reproduce this. Thanks for the report.

**Comment by raiguard** [comment]
I am unable to reproduce this issue, but I will keep trying. Sadly a fix won't make it into v1.5.1, because there are several other issues that have been fixed, that I would like to have out ASAP. Thanks again for the report. I'll let you know if I make any progress.

**Comment by raiguard** [comment]
As an aside, I really see no point to NOT using NetMonitor. It is superior in every way - more accurate tracking, working even when Rainmeter (or even your user!) are inactive, and tracking for several "hidden" adapters that Rainmeter wouldn't be able to track.

**Comment by raiguard** [comment]
I added some logic to prevent these readings from going negative. It doesn't solve the root cause of the issue, but it should be an acceptable workaround. Thanks for reporting this issue!

**Comment by zesquale** [comment]
Thanks for the update. I'll see to use NetMonitor.
Nevertheless, it looks like the issue is still happening in 1.6b6 :
![image](https://user-images.githubusercontent.com/49090868/59034227-de5c1b80-886a-11e9-9e9f-9ac21e90bcaf.png)
It's only the second time I see it happening, on 2 differents computers so it will be really difficult to reproduce :(.

Best Regards,

**Comment by raiguard** [comment]
The workaround is implemented in beta 7, which has not been released yet. I do have some suspicions as to the cause of this issue, but I'll have to wait until later to test my theory. Thanks for your help!

**Comment by raiguard** [comment]
I'm going to close this as I implemented a workaround, and the root issue is likely one with Rainmeter, not ModernGadgets. Thanks for the report!
